// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qflapwllxftcsdukoals.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmbGFwd2xseGZ0Y3NkdWtvYWxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3ODkyMDQsImV4cCI6MjA1ODM2NTIwNH0.Ez0BrQrftHkMz9H5hHG7uKcS43Gqsb74qPoa6JAz7QQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);